name: Push Docker Image

on:
  push:
    branches:
    - master
    paths-ignore:
    - '**.md'
 
env:
  DOCKERE_HUB_BASE_NAME: isoken26/web_container
  TAG_NAME: latest

jobs:
  push:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Build base image
      run: |
        docker build . -t isoken26/web_container:latest 

    - name: Login to Registrie
      env:
        DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      run: |
        echo "${DOCKER_HUB_TOKEN}" | docker login -u isoken26 --password-stdin
    
    - name: Push to Docker Hub
      run: docker push isoken26/web_container:latest  
